[project]
name = "rapperswil"
version = "0.1.0"
description = "Little API to generate calendars for Rapperswil-Jona"
requires-python = ">=3.13"
dependencies = [
    "fastapi~=0.128.0",
    "pydantic>=2.12.5",
    "python-dateutil>=2.9.0.post0",
    "recurrent>=0.4.1",
    "uvicorn==0.40.0",
    "jsonnet~=0.21.0",
    "icalendar>=6.3.2",
    "pytest>=9.0.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:.+parsedatetime.VERSION_CONTEXT_STYLE:PendingDeprecationWarning"
]
